baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Staines Portfolio'
theme = 'hugo-profile'

enableRobotsTXT = true

[params]
  title = "Staines Rajith"
  description = "Graduate Robotics, Mechatronics and Control Engineer"
  favicon = "images/favicon.ico"
  useBootstrapCDN = false
  animate = true

[params.theme]
  # disableThemeToggle = true
  defaultTheme = "light"

  [params.navbar]
    align = "ms-auto"
    brandName = "My Portfolio"
    brandLogo = "images/logo.png"  
    brandLogoWidth = "120px"       
    disableSearch = true
    stickyNavBar.enable = true
    stickyNavBar.showOnScrollUp = true
    enableSeparator = false
    menus.disableAbout = false
    menus.disableExperience = false
    menus.disableEducation = false
    menus.disableProjects = false
    menus.disableAchievements = false
    menus.disableContact = false

  [params.hero]
    enable = true
    intro = "Hi, my name is"
    title = "Staines Rajith"
    subtitle = "Graduate Robotics, Mechatronics & Control Engineer"
    content = "Mechatronics specialist with a passion for automation, robotics, and data-driven systems. Proven experience in industrial PLCs, embedded programming, and AI, aiming to push the boundaries of autonomous technologies."
    image = "images/my-photo.jpg"
    bottomImage.enable = true
    [params.hero.button]
      enable = true
      name = "Download CV"
      url = "/CV.pdf"
      download = true
      newPage = false
    [[params.hero.socialLinks.fontAwesomeIcons]]
      icon = "fab fa-github"
      url = "https://github.com/Spades2002"
    [[params.hero.socialLinks.fontAwesomeIcons]]
      icon = "fab fa-linkedin"
      url = "https://linkedin.com/in/stainesrajith"

  [params.about]
    enable = true
    title = "About Me"
    image = "images/my-photo4.jpg"
    content = """
As a Robotics and Control Engineering graduate, I bring together technical expertise and multicultural perspectives from my journey across India, Zambia, and the UK. My 15 years in Zambia instilled a deep appreciation for resourceful problem-solving through working with limited infrastructure, cross-cultural teamwork across diverse backgrounds, and sustainable design principles shaped by witnessing technology's real-world impact in developing communities.

My engineering passion focuses on practical automation - from PLCs and ROS to computer vision systems - always with an eye toward adaptable solutions. This technical mindset complements my creative side as a classically trained musician (Grade 6 Piano and Saxophone), where precision meets improvisation.

When not at my workbench, I'm usually on mountain bike trails, the squash court, or cross-country routes - physical disciplines that reinforce the focus and resilience I apply to engineering challenges. These combined experiences drive my interest in robotics solutions that bridge technological gaps between different global contexts.
"""


 [params.experience]
  enable = true
  [[params.experience.items]]
    job = "Retail Assistant"
    company = "Smyths Toy Store"
    date = "Nov 2024 - Dec 2024"
    content = """
- Enhanced customer experience by resolving complex product inquiries and guiding purchasing decisions through expert product knowledge
- Optimized store operations by reorganizing high-traffic displays and implementing efficient inventory tracking methods
- Maintained visual merchandising standards that increased product visibility and sales performance
- Streamlined stock management processes, reducing discrepancies and improving replenishment efficiency
"""

  [[params.experience.items]]
    job = "Control Engineering Intern"
    company = "First Quantum Minerals Ltd"
    date = "Jul 2022 - Aug 2022"
    content = """
- Optimized industrial equipment performance by collaborating with supervisors to maintain peak copper smelter efficiency
- Engineered a fully functional traffic light system using Siemens PLC and ladder logic, demonstrating advanced automation skills
- Mastered CODESYS programming using structured text and ladder logic to streamline industrial processes
- Presented comprehensive project results to management, showcasing problem-solving and technical expertise in PLC systems
"""

  [[params.experience.items]]
    job = "Teaching Assistant"
    company = "Trident College"
    date = "Jan 2021 - Mar 2021"
    content = """
- Elevated A-level student performance through targeted one-on-one tutoring in mathematics and sciences
- Designed and supervised laboratory experiments while enforcing strict safety standards
- Collaborated with faculty to develop engaging lesson materials that improved classroom outcomes
- Provided specialized music tutoring, helping students prepare for practical examinations
"""

  [[params.experience.items]]
    job = "Technical Team Assistant"
    company = "First Quantum Minerals Ltd"
    date = "Nov 2018 - Dec 2018"
    content = """
- Improved machinery reliability through proactive monitoring and maintenance in copper smelting operations
- Enhanced furnace performance by optimizing air cooler functionality and increasing airflow efficiency
- Prevented operational disruptions by identifying and reporting equipment abnormalities to supervisors
- Maintained 98% equipment uptime through rigorous adherence to safety and maintenance protocols
"""

[params.education]
  enable = true

  [[params.education.items]]
    title = "MSc Robotics and Artificial Intelligence"
    date = "Sep 2025 - Sep 2026"
    content = "Currently pursuing advanced studies in Robotics and AI"
    
    [params.education.items.school]
      name = "Queen Mary University of London"

  [[params.education.items]]
    title = "BEng Robotics, Mechatronics & Control Engineering"
    date = "Oct 2021 - Jun 2024"
    GPA = "Second Class Lower Division Honours"
    content = """
Key Projects:
- Eco-Friendly Intra-Campus Monorail System Design
- Gymnastics Stamp-bug and Rover
- Roll-angle measurement device

Key Modules:
- State Space Control
- Manufacturing Automation and Control Systems
- Electronics, Programming
- Interfacing with Mechatronics Systems
"""


  [params.achievements]
    enable = true
    title = "Certifications"
    [[params.achievements.items]]
      title = "EV Engineering Advanced Job Simulation"
      content = "Forage (Ford)"
    [[params.achievements.items]]
      title = "C++ Programming"
      content = "OpenEDG C++ Institute"
    [[params.achievements.items]]
      title = "Programming with Python"
      content = "OpenEDG Python Institute"
    [[params.achievements.items]]
      title = "Career Essentials in Software Development"
      content = "Microsoft"
    [[params.achievements.items]]
      title = "AutoCAD 2D"
      content = "CADD Centre Training Services Pvt. Ltd"
    [[params.achievements.items]]
      title = "Python"
      content = "Croma Campus Pvt. Ltd"
    [[params.achievements.items]]
      title = "AWS Release and Deploy"
      content = "edx"
    [[params.achievements.items]]
      title = "PLC Programming"
      content = "Udemy"
    [[params.achievements.items]]
      title = "Machine Learning at the edge"
      content = "Arm"

  [params.projects]
  enable = true
  [[params.projects.items]]
    title = "Engineering Job Finder"
    content = "Created a platform for finding engineering jobs using web scraping and NLP. Features include real-time job data retrieval from APIs, skills matching from resumes using NLP, and an interactive Streamlit interface with custom filters."
    image = "images/jobfinder.png"
    badges = ["Python", "NLP", "Web Scraping", "Streamlit"]
    [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/Spades2002/Other-Project-2"
  
  [[params.projects.items]]
    title = "Real-time Colour and Object Detection"
    content = "This real-time system combines YOLOv8 object detection with KNN color classification (trained on 865 named colors) via webcam. It merges deep learning and traditional ML, dynamically adjusting for lighting while highlighting objects and colors. Developed as a robotics perception prototype, it demonstrates integration of pre-trained models, real-time optimization, and modular vision task decomposition."
    image = "images/object detection.jpg"
    badges = ["OpenCV", "YOLOv8", "KNN", "Computer Vision"]
    [[params.projects.items.links]]
      icon = "fab fa-github"
      url = "https://github.com/Spades2002/Other-Project-1"

  [[params.projects.items]]
    title = "Eco-Friendly Intra-Campus Monorail System Design"
    content = "As project lead, I designed an eco-friendly intra-campus monorail for WSP, optimizing transport efficiency and sustainability. I conducted route analysis to maximize accessibility, minimize environmental impact, and integrate with existing infrastructure. The design featured high-capacity carriages with energy-efficient HVAC systems and elderly-friendly accommodations. Sustainable materials and propulsion methods were prioritized. Though conceptual, the project deepened my expertise in sustainable transport, infrastructure planning, and user-centered design—balancing efficiency, environmental responsibility, and passenger comfort."
    image = "images/monorail.jpg"
    badges = ["CAD", "Automation", "Sustainable Design"]
    featured = { name = "Download Report", link = "/Monorail project report.pdf" }


  [[params.projects.items]]
    title = "Roll-angle Measurement Device"
    content = "In this project, I developed a fibre optic Sagnac interferometer to measure axial rotation with high precision. After reviewing existing sensors and literature, I used an oscilloscope to capture and analyse data, validating the system’s performance. The setup leveraged the Sagnac effect to detect angular velocity, which was integrated to derive the roll angle. While the system accurately measured angular distance, it couldn’t determine rotation direction. The project enhanced my expertise in optical sensing and precision instrumentation."
    image = "images/roll-angle.png"
    badges = ["Sensors", "MATLAB", "Data Analysis"]
    featured = { name = "Download Literature Review", link = "/Interferometer literature review.pdf" }


  [[params.projects.items]]
    title = "Gymnastics Stamp-bug and Rover"
    content = "I led an engineering team in developing a robotic gymnastics rover that synchronized dynamic LED light displays with live performances. To achieve seamless audio-visual integration, I designed control algorithms for real-time responsiveness and optimized the system through iterative testing. Using Siemens NX, I incorporated sustainable materials and energy-efficient modifications. The project delivered a novel performance-enhancing system while advancing my expertise in embedded programming, robotics, and eco-conscious design. As the team lead, I also coordinated cross-disciplinary collaboration, balancing technical constraints with creative objectives."
    image = "images/stamp-bug.jpg"
    badges = ["Robotics", "Control Systems", "Mechatronics"]
    featured = { name = "Download Datasheet", link = "/Datasheet for stampbug.pdf" }


  [params.contact]
    enable = true
    content = "My inbox is always open for collaboration, questions, or just a friendly chat!"
    btnName = "Email Me"
    btnLink = "mailto:stainesr.27@gmail.com"

  [params.footer.socialNetworks]
    github = "https://github.com/Spades2002"
    linkedin = "https://linkedin.com/in/stainesrajith"

[markup.goldmark.renderer]
  unsafe = true
